"""empty message

Revision ID: 007ee2806a2b
Revises: 58f7d45befee
Create Date: 2023-05-16 08:25:05.195500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007ee2806a2b'
down_revision = '58f7d45befee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites__id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'characters', ['character_id'], ['id'])
        batch_op.drop_column('_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites__id_fkey', 'planets', ['_id'], ['id'])
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###
