"""empty message

Revision ID: 8101156ca0d6
Revises: 4be67a1870d1
Create Date: 2023-05-19 08:01:59.554116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8101156ca0d6'
down_revision = '4be67a1870d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorite_character')
    op.drop_table('favorite_planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_planet',
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planets_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], name='favorite_planet_planets_id_fkey'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='favorite_planet_users_id_fkey')
    )
    op.create_table('favorite_character',
    sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('characters_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], name='favorite_character_characters_id_fkey'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], name='favorite_character_users_id_fkey')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
